## Practical Session 1

In [25]:
import torch

### 1- Multiple views of a storage

In [79]:
test = torch.full((13,13),1)
test[[1,6,11]] = torch.full((1,13),2)
test[3:5,3:5] = 3
test[3:5,8:10] = 3
test[8:10,3:5] = 3
test[8:10,8:10] = 3
test

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 3, 3, 1, 1, 1, 3, 3, 1, 1, 1],
        [1, 1, 1, 3, 3, 1, 1, 1, 3, 3, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 3, 3, 1, 1, 1, 3, 3, 1, 1, 1],
        [1, 1, 1, 3, 3, 1, 1, 1, 3, 3, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

<h4><span style="color:green">  Corrections and improvements</span></h4>

<span style="color:green"> Using the skipping operator to tell to take every 5th element after the first</span>

### 2- Eigendecomposition

In [136]:
m = torch.randn((20,20),dtype=float)
## OR THE OTHER ONE
m[:2]

tensor([[ 0.9337,  0.8281,  0.2331, -0.2770, -0.7542,  0.1557,  0.6426,  1.6817,
         -1.1004,  0.4625,  0.3374,  0.6477,  1.3294, -0.2190,  0.6034, -0.2263,
          0.5705,  0.8141, -1.0350, -0.7232],
        [ 0.7026,  0.1989, -1.0787,  1.4165,  0.7295, -0.4421, -0.0135,  0.2450,
          0.4153, -1.0207,  0.2976, -0.3909, -0.2464, -1.9943, -0.7947,  0.8489,
         -1.2791,  1.0496,  0.6022, -0.1784]], dtype=torch.float64)

In [139]:
I_diag = torch.diag(torch.arange(1,21, dtype=float))
I_diag[:2]

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]], dtype=torch.float64)

In [132]:
m_inverse = torch.inverse(m)

In [155]:
multiplied_matrice = torch.matmul(torch.matmul(m_inverse, I_diag),m)
## OR
multiplied_matrice = first = torch.einsum('ij,jn,np -> ip', m_inverse, I_diag, m)
## OR
multiplied_matrice = m_inverse @ I_diag @ m
## OR 
m_inverse.mm(I_diag).mm(m)

multiplied_matrice[:2]

tensor([[-18.7782,  16.4204,   3.1781, -23.5145, -27.7152,  28.0064, -13.6036,
         -34.9269,   6.7157,  23.0589,   1.2905,  29.9443, -14.9327,  -1.3900,
           2.2292,  10.9479,   0.8179, -12.9492,  13.6066,   6.2198],
        [-20.3080,  14.7632,  72.2945, -44.2493, -28.9263,  40.0700,   4.5429,
         -90.3080,  -1.9323, 121.7385,  12.5760,  36.2063, -24.1218,  37.5601,
          -6.3237,  37.0623, -42.1075, -21.8138,   4.7429, -14.2962]],
       dtype=torch.float64)

In [159]:
torch.linalg.eig(multiplied_matrice).eigenvalues

tensor([ -1.0628+56.3971j,  -1.0628-56.3971j, -20.1095+27.7636j,
        -20.1095-27.7636j,  26.8798+0.0000j, -17.9450+0.0000j,
         10.5660+8.3062j,  10.5660-8.3062j,  -6.5545+3.9399j,
         -6.5545-3.9399j,   0.3332+8.3923j,   0.3332-8.3923j,
          4.4619+5.7564j,   4.4619-5.7564j,  -2.9950+0.0000j,
         -0.2045+2.7113j,  -0.2045-2.7113j,   1.5275+1.7692j,
          1.5275-1.7692j,  -0.3029+0.0000j], dtype=torch.complex128)

### 3- Flops per second

In [161]:
floppy_1 = torch.randn(5000,5000)
floppy_2 = torch.randn(5000,5000)

In [174]:
from time import perf_counter

t1_start = perf_counter()

floppy_1.mm(floppy_2)

t1_stop = perf_counter()

total_time = t1_stop - t1_start
print(f"Elapse time: {format(total_time)}")

Elapse time: 0.18597764900005131


In [176]:
format(2 * 5000 * 5000 * 5000 / total_time

'672123777626.4475'

<h4><span style="color:green">Correction</span></h4>

In [173]:
print('# 3 #')

d = 5000
a = torch.empty(d, d).normal_()
b = torch.empty(d, d).normal_()

time1 = time.perf_counter()
c = torch.mm(a, b)
time2 = time.perf_counter()

print('Throughput {:e} flop/s'.format((d * d * d)/(time2 - time1)))

# 3 #
Throughput 8.477179e+11 flop/s


<span style="color:green"> Wondering if the prof may have forgotten the times 2</span>

### 4- Playing with strides 

Version with python loop

In [200]:
def mul_row(tensor):
    for i, row in enumerate(tensor):
        tensor[i] = row * (i+1)
    return tensor

In [204]:
test = torch.full((4, 8), 2.0)
test

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]])

In [205]:
mul_row(test)

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [8., 8., 8., 8., 8., 8., 8., 8.]])

Version with tensor operations

In [261]:
def mul_row_fast(tensor):
    size = tensor.size(dim=0)
    return torch.mul(tensor,torch.arange(1, size+1).view(-1, 1))
    

In [247]:
test

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [8., 8., 8., 8., 8., 8., 8., 8.]])

In [246]:
mul_row_fast(test)

tensor([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
        [18., 18., 18., 18., 18., 18., 18., 18.],
        [32., 32., 32., 32., 32., 32., 32., 32.]])

In [249]:
test_final = torch.full((1000, 400), 2.0)


In [254]:
t1_start_slow = perf_counter()
mul_row(test_final)
t1_stop_slow = perf_counter()

print(format((t1_stop_slow - t1_start_slow)*60))

0.3330844199444982


In [255]:
t1_start_fast = perf_counter()
mul_row_fast(test_final)
t1_stop_fast = perf_counter()

print(format((t1_stop_fast - t1_start_fast)*60))

0.0247239600867033


In [257]:
(t1_stop_slow - t1_start_slow) / (t1_stop_fast - t1_start_fast)

13.472130628605614

In [262]:
print('# 4 #')

def mul_row(m):
    r = torch.torch.empty(m.size())
    for i in range(m.size(0)):
        for j in range(m.size(1)):
            r[i, j] = m[i, j] * (i + 1)
    return r

def mul_row_fast(m):
    c = torch.arange(1, m.size(0) + 1).view(-1, 1).float()
    return m.mul(c)

m = torch.empty(1000, 400).normal_()

time1 = time.perf_counter()
a = mul_row(m)
time2 = time.perf_counter()
b = mul_row_fast(m)
time3 = time.perf_counter()

print('Speed ratio', (time2 - time1) / (time3 - time2))

print('Sanity check: error is ', torch.norm(a - b).item())

######################################################################

# 4 #
Speed ratio 7336.207057125469
Sanity check: error is  0.0


In [264]:
mul_row_fast(test)

tensor([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
        [18., 18., 18., 18., 18., 18., 18., 18.],
        [32., 32., 32., 32., 32., 32., 32., 32.]])

In [260]:
a

tensor([[-2.3978e+00, -4.8750e-01, -6.9742e-01,  ..., -2.3053e-01,
          5.9751e-01,  1.7306e+00],
        [ 4.4475e+00,  1.0963e+00,  6.7468e-01,  ...,  8.4165e-01,
          2.8812e+00, -9.8924e-02],
        [ 1.5434e+00,  5.7728e-01, -8.0986e-01,  ...,  2.0347e-01,
         -1.7115e+00, -3.0562e+00],
        ...,
        [ 2.0320e+03,  3.1475e+02, -7.3569e+01,  ...,  1.4564e+03,
          3.9009e+02, -6.5183e+02],
        [-9.6659e+02, -6.8061e+02, -7.8808e+02,  ...,  5.9792e+02,
         -7.6895e+02, -1.9147e+03],
        [ 6.7628e+02,  3.0361e+02,  5.1429e+02,  ..., -4.4779e+02,
          3.0695e+02,  9.1228e+02]])

In [265]:
test

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [8., 8., 8., 8., 8., 8., 8., 8.]])

<span style="color:green">I probably had a better loop from the getgo which explains the difference in perf ratio.</span>